//! Wire protocol between the GUI and the elevated helper process.
//!
//! Transport: newline-delimited JSON, one request per TCP connection to
//! `127.0.0.1:<port>`. The port is published by the helper in a port file;
//! every request carries the shared-secret token from the 0600 token file
//! (the helper re-reads that file on each request, so a new GUI session can
//! re-key a still-running helper just by rewriting the file).
//!
//! This module is compiled into both the GUI (`mod helper_ipc`) and the
//! helper binary (`#[path] mod`), so the two sides can never drift. Each
//! side only calls part of it (the GUI sends, the helper builds responses),
//! hence the file-level dead_code allow.
#![allow(dead_code)]

use serde::{Deserialize, Serialize};
use std::io::{BufRead, BufReader, Write};
use std::net::TcpStream;
use std::time::Duration;

// --- macOS LaunchDaemon mode (SMAppService) ---------------------------------
// In daemon mode the helper is a root launchd daemon, so the port/token files
// live at fixed system paths instead of the GUI user's app-data dir, and the
// TOKEN IS GENERATED BY THE DAEMON (root:admin 0640) rather than by the GUI —
// only admin-group users can command the always-running daemon.

/// Root-owned directory where the daemon publishes its port and token.
#[cfg(target_os = "macos")]
pub const DAEMON_DIR: &str = "/Library/Application Support/io.github.madeye.shadowvpn.desktop";
#[cfg(target_os = "macos")]
pub const DAEMON_PORT_FILE: &str =
    "/Library/Application Support/io.github.madeye.shadowvpn.desktop/helper.port";
#[cfg(target_os = "macos")]
pub const DAEMON_TOKEN_FILE: &str =
    "/Library/Application Support/io.github.madeye.shadowvpn.desktop/helper.token";
/// Name of the plist bundled in Contents/Library/LaunchDaemons/.
#[cfg(target_os = "macos")]
pub const DAEMON_PLIST_NAME: &str = "io.github.madeye.shadowvpn.desktop.helper.plist";

#[derive(Serialize, Deserialize)]
#[serde(tag = "cmd", rename_all = "snake_case")]
pub enum Cmd {
    /// Liveness + identity probe.
    Ping,
    /// Start the client with `-c <profile>`, appending output to `log` and
    /// writing the child PID to `pid_file` before responding.
    Connect {
        profile: String,
        log: String,
        pid_file: String,
    },
    /// Stop the helper's client child (graceful where the OS allows it).
    Disconnect,
    /// Run the client binary with `--restore-dns` to heal the system resolver:
    /// apply the journal a crashed run left behind, or — if there is no
    /// journal but DNS is still `127.0.0.1` — reset to automatic/DHCP.
    /// Refused while a client child is running (the live client owns the
    /// resolver configuration).
    RestoreDns,
    /// Stop the client child if any, remove the port file, and exit.
    Shutdown,
}

#[derive(Serialize, Deserialize)]
pub struct Request {
    pub token: String,
    #[serde(flatten)]
    pub cmd: Cmd,
}

#[derive(Serialize, Deserialize, Default)]
pub struct Response {
    pub ok: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pid: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub running: Option<bool>,
    /// Echoed by `ping`: the client binary this helper was spawned for (a
    /// helper never executes any other program).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub client_bin: Option<String>,
}

impl Response {
    pub fn err(msg: impl Into<String>) -> Self {
        Response {
            ok: false,
            error: Some(msg.into()),
            ..Default::default()
        }
    }
}

pub const CONNECT_TIMEOUT: Duration = Duration::from_secs(2);
/// Generous enough to cover a graceful-stop wait inside the helper (10s).
pub const IO_TIMEOUT: Duration = Duration::from_secs(30);
/// Liveness probes must fail fast: a stale port file can point at an
/// unrelated local listener (macOS `rapportd` reused the daemon's last port),
/// and waiting [`IO_TIMEOUT`] on that socket is what made Connect hang.
pub const PING_CONNECT_TIMEOUT: Duration = Duration::from_millis(400);
pub const PING_TIMEOUT: Duration = Duration::from_millis(500);

/// One request/response round-trip on a fresh connection.
pub fn call(port: u16, req: &Request) -> Result<Response, String> {
    call_with_io_timeout(port, req, IO_TIMEOUT)
}

/// Same round-trip with a caller-chosen I/O deadline. App-exit teardown uses
/// a short one: quitting must never hang the UI thread for the full
/// [`IO_TIMEOUT`] on a wedged helper.
pub fn call_with_io_timeout(
    port: u16,
    req: &Request,
    io_timeout: Duration,
) -> Result<Response, String> {
    call_with_timeouts(port, req, CONNECT_TIMEOUT, io_timeout)
}

/// Round-trip with caller-chosen connect and I/O deadlines. Pings use the
/// short [`PING_CONNECT_TIMEOUT`] / [`PING_TIMEOUT`] pair.
pub fn call_with_timeouts(
    port: u16,
    req: &Request,
    connect_timeout: Duration,
    io_timeout: Duration,
) -> Result<Response, String> {
    let addr = std::net::SocketAddr::from(([127, 0, 0, 1], port));
    let stream = TcpStream::connect_timeout(&addr, connect_timeout)
        .map_err(|e| format!("cannot reach helper on 127.0.0.1:{port}: {e}"))?;
    let _ = stream.set_read_timeout(Some(io_timeout));
    let _ = stream.set_write_timeout(Some(io_timeout));

    let mut line = serde_json::to_string(req).map_err(|e| e.to_string())?;
    line.push('\n');
    let mut writer = stream.try_clone().map_err(|e| e.to_string())?;
    writer
        .write_all(line.as_bytes())
        .map_err(|e| format!("helper write failed: {e}"))?;

    let mut reader = BufReader::new(stream);
    let mut resp_line = String::new();
    reader
        .read_line(&mut resp_line)
        .map_err(|e| format!("helper read failed: {e}"))?;
    serde_json::from_str(&resp_line).map_err(|e| format!("bad helper response: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::net::TcpListener;
    use std::thread;
    use std::time::Instant;

    #[test]
    fn ping_timeout_does_not_wait_full_io_timeout() {
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let port = listener.local_addr().unwrap().port();
        thread::spawn(move || {
            // Accept and hold the connection without ever sending a line —
            // the stale-port / rapportd case.
            let Ok((_stream, _)) = listener.accept() else {
                return;
            };
            thread::sleep(Duration::from_secs(60));
        });
        let req = Request {
            token: "x".into(),
            cmd: Cmd::Ping,
        };
        let start = Instant::now();
        let err = match call_with_timeouts(port, &req, PING_CONNECT_TIMEOUT, PING_TIMEOUT) {
            Err(e) => e,
            Ok(_) => panic!("ping unexpectedly succeeded against a silent listener"),
        };
        let elapsed = start.elapsed();
        assert!(
            elapsed < Duration::from_secs(3),
            "ping hung for {elapsed:?}: {err}"
        );
    }
}
